### ISSUE TITLE
Exercise 4.2-3, dudas issues #4 y #5

### ISSUE THREAD

**Issue by Tokytome** [Adalab/soluciones-ejercicios-front#6]
## Exercise 4.2-3, dudas issues #4 y #5

Se plantea el uso de
```javascript 
return Math.pow(this.base,2); 
 ```
como otra solución, pero creo que no sería correcto, dado que para el area del triangulo se usa 
```javascript
return super.area() / 2; 
```
y en ese caso la altura no es igual al lado.

Se pide en el ejercicio

> “Un atributo lado (`side`) igual a la base”

que habría que añadir explícitamente:
```javascript
class Square extends Polygon {
  constructor(squareSide) {
    super(4, squareSide, squareSide);
    this.side = this.base;  // <= esto
  }
}
```
De esta manera `Square` posee el atributo `side` que es igual a base. Para sustituirlo en el Ejercicio Bonus, entendí que habría que añadirlo antes.

Una última pregunta, ¿cuál es la fórmula que estamos siguiendo para el cálculo de áreas de los polígonos regulares? En teoría, debería ser:

`perímetro * apotema / 2`

pero en los ejercicios no estamos usando el perímetro, además de que altura y apotema no es lo mismo. Estoy confusa :dizzy_face:

**Comment by Roboe** [comment]
Sí, ayer vimos que cometí un error al escribir el ejercicio 4.2-3: https://github.com/Adalab/soluciones-ejercicios-front/pull/4#discussion_r162796743 Disculpas.

En el ejercicio bonus A tienes que usar _getters_ y _setters_ para **emular** un atributo `side`.

Estamos usando las fórmulas básicas `lado * lado` para el cuadrado y `base * altura / 2` para el triángulo. No pretende ser una clase de geometría, así que se indican en cada caso, :)

**Comment by guerrero** [comment]
Una cosa que quizás haya que mencionar sería cómo calcular la altura de un triángulo equilatero en función de la longitud de su base (`Math.sqrt(Math.pow(lado / 2) * Math.pow(lado))`)

**Comment by gootyfer** [comment]
@guerrero no hace falta. Trabajamos con cualquier tipo de triángulo y por tanto nos pasan los dos datos ;)

**Comment by guerrero** [comment]
Pero si pasan una altura diferente a `Math.sqrt(Math.pow(lado / 2) * Math.pow(lado))` se convertirá en un triángulo isosceles y por tanto todos los lados ya no serán iguales y habrá que cambiar la fórmula del perímetro

**Comment by Roboe** [comment]
Es cierto, pero en el ejercicio se pasa base 4 y altura 3, que es un equilátero... no quería añadir geometría, es un ejercicio de programación

**Comment by Tokytome** [comment]
Una solución podria ser incluir un método que calcule el apotema?

`Apotema = 360º/ numeroDeLados`

De esta manera podemos prescindir de la altura y el método del area serviría para todos los polígonos regulares

**Comment by Tokytome** [comment]
Pido perdón si mi mensaje ha parecido un poco borde. Preguntaba porque soy una preguntona :sweat:

Comprendo que no se trata de un ejercicio de geometría. Simplemente, por usar esa nomenclatura, a veces no estaba segura de si estaba implementando la funcionalidad correctamente.

**Comment by guerrero** [comment]
Bueno aclarado todo, cierro el issue. Creo que como dice @Roboe no tiene sentido complicar más el ejercicio, no me había fijado en que el triángulo que se crea es equilatero, asi que creo que no es necesario complicarlo más y que no se convierta en una clase de trigonometría.
